export const notificationsData = [
    {
        id: 1,
        type: "order",
        title: "New order received",
        description: "Order #5102938 placed by Linda Park for Nintendo Switch.",
        time: "2 min ago",
        read: false,
    },
    {
        id: 2,
        type: "user",
        title: "New user registered",
        description: "Carlos Rivera just created an account.",
        time: "15 min ago",
        read: false,
    },
    {
        id: 3,
        type: "delivery",
        title: "Shipment delivered",
        description: "TRK-003 delivered to Michael Doe in Chicago.",
        time: "1 hour ago",
        read: false,
    },
    {
        id: 4,
        type: "warning",
        title: "Low stock alert",
        description: "PlayStation 5 has only 8 units left in stock.",
        time: "3 hours ago",
        read: true,
    },
    {
        id: 5,
        type: "success",
        title: "Payment confirmed",
        description: "Payment of $1,450 received for Order #3124567.",
        time: "5 hours ago",
        read: true,
    },
    {
        id: 6,
        type: "warning",
        title: "Shipment delayed",
        description: "TRK-004 to Emily Rose is delayed due to weather conditions.",
        time: "Yesterday",
        read: true,
    },
    {
        id: 7,
        type: "info",
        title: "System maintenance scheduled",
        description: "Planned maintenance on March 15 from 02:00 to 04:00 UTC.",
        time: "Yesterday",
        read: true,
    },
    {
        id: 8,
        type: "order",
        title: "Order cancelled",
        description: "Order #3987654 by Tom Blake has been cancelled.",
        time: "2 days ago",
        read: true,
    },
    {
        id: 9,
        type: "success",
        title: "Refund processed",
        description: "Refund of $1,350 issued successfully to Emily Rose.",
        time: "2 days ago",
        read: true,
    },
    {
        id: 10,
        type: "info",
        title: "New product added",
        description: 'iPad Pro 12.9" has been added to the product catalog.',
        time: "3 days ago",
        read: true,
    },
];
